# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Debugging Challenge Unit 02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Debugging Challenge Unit 02
  pod "AlamofireImage"

  target 'Debugging Challenge Unit 02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Debugging Challenge Unit 02UITests' do
    # Pods for testing
  end

end
