# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Debugging Challenge Unit 01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Debugging Challenge Unit 01
   pod "AlamofireImage"
   
  target 'Debugging Challenge Unit 01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Debugging Challenge Unit 01UITests' do
    # Pods for testing
  end

end
